PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE t_ip(id integer primary key autoincrement,address text,center_name text,center_position text);
INSERT INTO "t_ip" VALUES(4,'192.1.1.1','东北大学','辽宁省沈阳市和平区');
INSERT INTO "t_ip" VALUES(5,'192.1.1.2','中船信息','月坛北街5号');
INSERT INTO "t_ip" VALUES(6,'192.1.1.3','esdtek',' 知春路51号');
INSERT INTO "t_ip" VALUES(7,'192.1.1.4','百度','西二旗地铁');
INSERT INTO "t_ip" VALUES(8,'192.1.1.5','联想','西二旗地铁');
INSERT INTO "t_ip" VALUES(9,'192.1.1.6','一起装修网','和平里北街');
INSERT INTO "t_ip" VALUES(10,'192.1.1.7','神州数码','西二旗');
INSERT INTO "t_ip" VALUES(11,'192.1.1.8','小米科技','五彩城');
INSERT INTO "t_ip" VALUES(12,'192.1.1.9','搜狐','五道口');
INSERT INTO "t_ip" VALUES(13,'192.1.1.10','网易','五道口');
INSERT INTO "t_ip" VALUES(14,'192.1.1.11','腾讯视频','知春路');
CREATE TABLE t_user(id integer primary key AUTOINCREMENT,user_name text,password text,email text,last_login integer,last_ip text,salt text,status integer);
INSERT INTO "t_user" VALUES(1,'admin','7fef6171469e80d32c0559f88b377245','admin@example.com',1460247521,'127.0.0.1','',0);
CREATE TABLE t_protocol(id integer primary key autoincrement,com integer,baud_rate integer,data_bit integer,parity_bit integer,stop_bit integer);
INSERT INTO "t_protocol" VALUES(1,1,3,8,0,0);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('t_ip',14);
INSERT INTO "sqlite_sequence" VALUES('t_user',1);
INSERT INTO "sqlite_sequence" VALUES('t_protocol',1);
COMMIT;
